### ISSUE TITLE
Turn off automatic open for both dev server and storybook

### ISSUE THREAD

**Issue by ductiletoaster** [pixeloven/pixeloven#14]
# Need to turn off auto browser functionality if inside docker
    # --ci for storybook

**Comment by jimmynotjim** [comment]
Honestly, I have to restart storybook so often to clear the test file cache that I would love to kill this everywhere. As long as the final output on start prints the port when using localhost, I think we'd be fine.

**Comment by ductiletoaster** [comment]
should be easy to configure but yeah I can just make it always off.

**Comment by ductiletoaster** [comment]
Fixed here: https://github.com/pixeloven/pixeloven/pull/31
