### ISSUE TITLE
Make path in Storybook config configurable in outside projects

### ISSUE THREAD

**Issue by jimmynotjim** [pixeloven/pixeloven#160]
**Describe the bug**
When attempting to run Storybook in a project without a `/shared` directory Storybook fails with the following errors:

```
ERROR in [...]/node_modules/@pixeloven/storybook/dist/lib/config/config.js
Module not found: Error: Can't resolve '@src/shared' in '[...]/node_modules/@pixeloven/storybook/dist/lib/config'

ERROR in [...]/node_modules/@pixeloven/storybook/dist/lib/config/config.js
Module not found: Error: Can't resolve '@src/shared/styles' in '[...]/node_modules/@pixeloven/storybook/dist/lib/config'
```

**To Reproduce**
1. Create a new project with Pixeloven Storybook
2. Run `pixeloven story start`
3. See the above errors

**Expected behavior**
Allow the config to be modified by individual projects

**Environment (please complete the following information):**
 - Operating System: MacOS 10.14.116
 - Package Manager & Version: yarn 1.13.0
 - Node Version: 10.8.0

**Comment by ductiletoaster** [comment]
To support basic TS compilation of react components with assets we need a new CLI script to help copy files. Our CLI supports globbing so we just need to use the built in functions to copy over assets. 

As a quick pass I have created a script to do this.
**pixeloven/packages/examples/component-library-example**
`copyfiles -u 1 \"src/**/*.{scss,svg}\" ./dist/lib
`

https://github.com/pixeloven/pixeloven/issues/164
