### ISSUE TITLE
Storybook can't resolve absolute paths

### ISSUE THREAD

**Issue by ductiletoaster** [pixeloven/pixeloven#21]
https://github.com/storybooks/storybook/issues/3916

Can't do absolute paths

**Comment by jimmynotjim** [comment]
Tested this solution and it works. https://medium.com/@ktruong008/absolute-imports-with-create-react-app-4338fbca7e3d. Thoughts on doing the same and moving away from the @ name spaced paths?

**Comment by ductiletoaster** [comment]
We should be able to handle these pretty easily. Just need to add a plugin that reads TSConfig into storybook. Testing a solution right now.

**Comment by ductiletoaster** [comment]
https://github.com/pixeloven/pixeloven/pull/33
