### ISSUE TITLE
Include all of /shared in storybook

### ISSUE THREAD

**Issue by jimmynotjim** [pixeloven/pixeloven#22]
**Is your feature request related to a problem? Please describe.**
Storybook only watches `/shared/components` but we'd also like to include non-component stories in /styes or /base to showcase non-component elements.

**Describe the solution you'd like**
Update Storybook to watch all of `/shared`.

**Comment by ductiletoaster** [comment]
Fix in master

**Comment by jimmynotjim** [comment]
![giphy](https://media.giphy.com/media/FlWgXEtj5aM5G/giphy.gif)
