### ISSUE TITLE
Upgrade to Storybook 4.1

### ISSUE THREAD

**Issue by jimmynotjim** [pixeloven/pixeloven#61]
**Is your feature request related to a problem? Please describe.**
Storybook 4.1 has dropped and runs much faster and expands compatibility (not necessarily an issue we have). https://medium.com/storybookjs/storybook-4-1-need-for-speed-b05fd5f1e83d

**Describe the solution you'd like**
 Would be nice to upgrade and give v4.1 the ol' tire kick.

**Comment by ductiletoaster** [comment]
Along with this we should upgrade our react versions (and/or set better peerDeps)
