### ISSUE TITLE
Make browser opening an option

### ISSUE THREAD

**Issue by jimmynotjim** [pixeloven/pixeloven#82]
**Is your feature request related to a problem? Please describe.**
Most of us have a browser window/tab going for development on both the app and storybook. Auto-opening causes a whole lotta tabs or constantly closing them. 

**Describe the solution you'd like**
Make auto opening the browser a command flag so that users that want it can use it but those that don't, don't have to worry about it.

**Describe alternatives you've considered**
Making it a config entry, but that seems less obvious to future users.

**Comment by ductiletoaster** [comment]
I think I'm going to boot this feature for now. We have a lot going on already and I don't think most of us miss this since we tend to run the app in docker anyway.

**Comment by jimmynotjim** [comment]
👍 I haven't missed it at all.
